name: metting_app
description: Ứng dụng quản lý cuộc họp
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  flutter_local_notifications: ^17.0.0
  image_picker: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  google_fonts: ^5.1.0
  flutter_secure_storage: ^8.0.0
  json_annotation: ^4.8.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.9.4
  google_sign_in: ^6.2.2
  curved_navigation_bar: ^1.0.6
  hugeicons: ^0.0.7
  path: ^1.8.3
  uuid: ^4.2.1
  # sqflite: ^2.3.0
  sqflite: any
  flutter_zoom_drawer: ^3.1.1
  iconly: ^1.0.1
  # File management
  file_picker: ^8.0.7
  path_provider: ^2.1.4
  url_launcher: ^6.2.5
  # Analytics
  device_info_plus: ^10.1.2
  package_info_plus: ^8.0.2
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/images/main_top.png
    - assets/images/signup_top.png
    - assets/images/login_bottom.png
    - assets/images/main_bottom.png
    - assets/images/.gitkeep
    - assets/icons/.gitkeep
    - assets/fonts/.gitkeep 